package org.multigraph;

/**
 * DataFormatters are used to convert DataValues to strings, according
 * to a particular conversion/formatting pattern.  This is an abstract
 * superclass; the actual work is done by datatype-specific subclasses.
 */
public abstract class DataFormatter {

    /**
     * String containing the format pattern for this DataFormatter.
     */
    protected String mFormat;

    /**
     * Subclass constructors should call super(format) to set the format string property.
     */
    protected DataFormatter(String format) {
        this.mFormat = format;
    }

    /**
     * Return the string that results from formatting a specific DataValue using
     * this DataFormatter's format string. 
     *
     * @param value  The DataValue to be converted.
     *
     * @return A String that is the result of the conversion.
     */
    abstract public String format(DataValue value);


    /**
     * Return the maximum string length of strings (typically) returned
     * by this DataFormatter.  This may be an estimate and might not include
     * lengths generated by unusually large values.
     *
     * @return The maximum string length.
     */
    abstract public int getMaxLength();

}
